packages:
  - "packages/*"
  - "examples/*"
  - "docs"
  - "test"
gitChecks: false
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@swc/core"
  - "@vercel/speed-insights"
  - better-sqlite3
  - esbuild
  - playwright-chromium
  - simple-git-hooks
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  "@voidzero-dev/vite-plus": latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
